plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

group = 'io.github.larsarv.jrmg'
version = '1.0.5'

repositories {
    mavenCentral()
}

dependencies {
}

test {
    useJUnitPlatform()
}

tasks.named('wrapper') {
    gradleVersion = "9.2.1"
}